### ISSUE TITLE
add penalty list api endpoint

### ISSUE THREAD

**Issue by hclivess** [hclivess/nado#34]

**Comment by majordutch** [comment]
If you have time to further define this, I can probably take it.

**Comment by hclivess** [comment]
Thanks, I will provide more details in the morning

**Comment by hclivess** [comment]
Target storage would be in memserver, let's say `memserver.penalties` and would be a dictionary, initialized as empty.
At this moment, there's `get_penalty()`, which is used by `pick_best_producer()`. I'm thinking `pick_best_producer()` should populate `memserver.penalties` when block is generated so no additional calculation is done by the node.

Also block producers change, so the dictionary should be emptied every time before it is filled in.

It should be fairly straightforward, let me know if you need anything.

**Comment by hclivess** [comment]
Best option would be if the dictionary would be filled in a level above (because block_ops.py is a low level function) rather than passign the dict into it, but those functions already return their specific values, so I'm open to clean and creative solutions to that problem

**Comment by hclivess** [comment]
Then on the endpoint something like `/penalties` to view that dicionary
